goldtask\Bundle\AppBundle\Entity\clockindetails:
    type: entity
    table: null
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
            strategy: IDENTITY
    fields:
        userid:
            type: integer
        officesId:
            type: integer
            column: offices_id
        startDate:
            type: datetime
            column: start_date
        endDate:
            type: datetime
            column: end_date
        timeDiff:
            type: decimal
            nullable: true            
            scale: 10
            precision: 2
            column: time_diff
        weight:
            type: decimal
            nullable: true            
            scale: 10
            precision: 2
            column: weight
        sessionIds:
            type: string
            column: session_ids
        isStatus:
            type: integer
            column: is_status
        createdBy:
            type: integer
            column: created_by
        createdOn:
            type: datetime
            column: created_on
        updatedBy:
            type: integer
            column: updated_by
        updatedOn:
            type: datetime
            column: updated_on
    lifecycleCallbacks: {  }
