goldtask\Bundle\AppBundle\Entity\UserPasswordUpdates:
    type: entity
    table: user_password_updates
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: user_id
        randomCode:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
            column: random_code
        isDone:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
            column: is_done
        isExpired:
            type: boolean
            nullable: true
            comment: ''
            default: '0'
            column: is_expired
        createdOn:
            type: datetime
            nullable: false
            comment: ''
            column: created_on
    lifecycleCallbacks: {  }
