goldtask\Bundle\AppBundle\Entity\UserAccess:
    type: entity
    table: user_access
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: user_id
        loggedIp:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            column: logged_ip
        loggedBrowser:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: logged_browser
        loggedAt:
            type: datetime
            nullable: true
            comment: ''
            column: logged_at
        logoutAt:
            type: datetime
            nullable: true
            comment: ''
            column: logout_at
        loggedStatus:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: ''
            column: logged_status
        logoutStatus:
            type: string
            nullable: true
            length: 10
            fixed: false
            comment: ''
            column: logout_status
        sessionId:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            column: session_id
    lifecycleCallbacks: {  }
