goldtask_app_homepage:
    pattern:  /
    defaults: { _controller: goldtaskAppBundle:Default:index }

register:
    pattern: /register
    defaults: { _controller: goldtaskAppBundle:Register:register }

about:
    pattern: /about
    defaults: { _controller: goldtaskAppBundle:Default:about }

article:
    pattern: /article
    defaults: { _controller: goldtaskAppBundle:Default:article }

services:
    pattern: /services
    defaults: { _controller: goldtaskAppBundle:Default:services }

news:
    pattern: /news
    defaults: { _controller: goldtaskAppBundle:Default:news }

contact:
    pattern: /contact
    defaults: { _controller: goldtaskAppBundle:Default:contact }

article:
    pattern: /article
    defaults: { _controller: goldtaskAppBundle:Default:article }

login:
    pattern: /login
    defaults: { _controller: goldtaskAppBundle:Register:login }

changepassword:
    pattern: /changepassword
    defaults: { _controller: goldtaskAppBundle:Register:changePassword }

forgotpassword:
    pattern: /forgotpassword
    defaults: { _controller: goldtaskAppBundle:Register:forgotPassword }

myprofile:
    pattern: /myprofile
    defaults: { _controller: goldtaskAppBundle:Register:myprofile }

userslist:
    pattern: /userslist
    defaults: { _controller: goldtaskAppBundle:Register:usersList }
usersupdate:
    pattern: /usersupdate/{id}
    defaults: { _controller: goldtaskAppBundle:Register:usersUpdate }

usersdelete:
    pattern: /usersdelete/{id}
    defaults: { _controller: goldtaskAppBundle:Register:usersDelete }
    
usersactive:
    pattern: /usersactive/{id}
    defaults: { _controller: goldtaskAppBundle:Register:usersActive }

usersinactive:
    pattern: /usersinactive/{id}
    defaults: { _controller: goldtaskAppBundle:Register:usersInactive }

usersblocked:
    pattern: /sellersblocked/{id}
    defaults: { _controller: goldtaskAppBundle:Register:usersBlocked }

usersunblocked:
    pattern: /sellersunblocked/{id}
    defaults: { _controller: goldtaskAppBundle:Register:usersUnblocked }

usersview:
    pattern: /usersview/{id}
    defaults: { _controller: goldtaskAppBundle:Register:usersView }

changepassword:
    pattern: /changepassword
    defaults: { _controller: goldtaskAppBundle:Register:changepassword }

resetpassword:
    pattern: /resetpassword
    defaults: { _controller: goldtaskAppBundle:Register:resetpassword }	
logout:
    pattern: /logout
    defaults: { _controller: goldtaskAppBundle:Register:logout }
addOffice:
    pattern: /addOffice
    defaults: { _controller: goldtaskAppBundle:Offices:addOffice }
officeslist:
    pattern: /officeslist
    defaults: { _controller: goldtaskAppBundle:Offices:officeslist }
officeview:
    pattern: /officeslist/{id}
    defaults: { _controller: goldtaskAppBundle:Offices:officeslist }
officeupdate:
    pattern: /officeupdate/{id}
    defaults: { _controller: goldtaskAppBundle:Offices:officeupdate }
officedelete:
    pattern: /officedelete/{id}
    defaults: { _controller: goldtaskAppBundle:Offices:officedelete }
customer:
    pattern: /customer
    defaults: { _controller: goldtaskAppBundle:Clockin:customer }
clockinlist:
    pattern: /clockinlist
    defaults: { _controller: goldtaskAppBundle:Clockin:clockinlist }
clockoutlist:
    pattern: /clockoutlist
    defaults: { _controller: goldtaskAppBundle:Clockin:clockoutlist }
clockin:
    pattern: /clockin
    defaults: { _controller: goldtaskAppBundle:Clockin:clockin }	
captcha:
    pattern:  /captcha
    defaults: { _controller: "goldtaskAppBundle:Register:captcha" }	
username_finding:
    pattern: /username_finding
    defaults: { _controller: goldtaskAppBundle:Register:username_finding }
username_email_finding:
    pattern: /username_email_finding
    defaults: { _controller: goldtaskAppBundle:Register:username_email_finding }
managerslist:
    pattern:	/managerslist
    defaults: { _controller: goldtaskAppBundle:Register:managerslist }
wrong:
    pattern: /wrong
    defaults: { _controller: goldtaskAppBundle:Register:wrong}
sample_code_get_json:
    pattern: /sample_code_get_json
    defaults: { _controller: goldtaskAppBundle:Clockin:sample_code_get_json}
